### PR TITLE
Fixing Some of the Dashboard Issues

### LINKED ISSUE #16: Fix the responsiveness of the HomePage
- To save time and focus on other parts like backend, I created this webpage with the help of figma and used locofy-ai to generate the react code. 

- As you can see the responsiveness is not that great for the homepage when we shrink it, Solving this would be much appreciable. 

- You can comment if your are interested.

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
# Main Problem
Closes #16 to some extent

## Fixed Problems
- [x] Center Aligned the items properly, and it works on most devices
- [x] Fixed the Footer
- [x] Fixed the Courses Section
- [x] Fixed the Breaking of hero section

- In my opinion I think it is better to have a smaller (max-width:1920px) section than a broken one so I did that
- I think I can't do anymore changes else it will break one thing or the other

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Hey @Thunder-Blaze , I can see some sections are breaking out in your current PR. Yea, I have to refactor the whole dashboard because its going to be a long process. I cant merge your PR due to this and If you are willing to work on some other issues, let me know or you can create your own issue if you find something wrong and you can fix that.

Thanks!

**Comment by Thunder-Blaze** [comment]
@VishnuAmit Sir I think I've already made the footer responsive in my design, you can check it so I think there's no need for #23
I'll refactor some of the code and try to make the website responsive
just give me 2-3 days please

**Comment by VishnuAmit** [comment]
hey @Thunder-Blaze, sorry for the delay.
Can you fix the other  content overlapping with the footer `(issue 1)`
image

The zoomed in homepage is below attached `(issue 2)`
image

The normal one is 
image


And looks like you are interested to make the whole homepage responsive. You can take your time and there is no rush. There are no restrictions to your ideas apart from changing the font colors, cards and content. You can make each section responsive if you are willing to.

About the navbar, make it sticky and hamburger for mobile screens.


If you want me to merge this PR, kindly fix the  `issue 1` and `issue 2`  or you can take your own time and finish up everything and create a new PR/modify the existing. (your choice)

Any more doubts, You can ask!

**Comment by Thunder-Blaze** [comment]
I closed it because I'll be making a new PR for it, There had been merge conflicts since somebody else had contributed in some of the files I modified

**Comment by VishnuAmit** [comment]
alright @Thunder-Blaze .

**Pull request closed without merging**
