### PR TITLE
Enhancement of Dashboard UI

### PR DESCRIPTION
**Pull request by ArpitaAgrahari**
#4 This pull request includes multiple commits that refactor the component styles to improve readability and user experience. The changes are focused on various components such as LearningPaths, PlatformOverview, Testimonials, SmartNotesCard, FrameComponent4, SignUpScreen, LatestUpdates, and Footer. The styles have been updated to enhance typography consistency, button alignment, image positioning, and overall visual appeal. These changes aim to provide a better user experience and make the code more maintainable.

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Hey @ArpitaAgrahari , Thanks for your time but could you please look into this. The changes you made in testimonial has affected this.


Thanks!

**Comment by ArpitaAgrahari** [comment]
Hey, @VishnuAmit, I made the changes, and it was working well before. I also fixed that issue before submitting the PR, and it’s working perfectly now. You can check out the screenshots for reference.
Screenshot 2024-10-02 092634
Screenshot 2024-10-02 092647

**Comment by ArpitaAgrahari** [comment]
Please label the appropriate level on my recent pull request under gssoc-24 extd. and hacktoberfest

**Comment by VishnuAmit** [comment]
Hey, It has been done already and added gssoc-24 label now.

**Comment by ArpitaAgrahari** [comment]
Level as in "Level 1/Level 2/Level 3" label has not been added yet ! Do the needful on both PR and the issue.

**Comment by VishnuAmit** [comment]
Is it fine, now?

**Comment by ArpitaAgrahari** [comment]
Yeah, thank you!!

**Pull request merged**
