### PR TITLE
Fixed overall footer Responsiveness and the alignment of text in email 

### PR DESCRIPTION
**Pull request by BarryByte**
### Explanation of the changes:
- **`text-center` class**: This ensures the text and the placeholder in the input field is centered.
- **`w-full`**: The input now takes the full available width, making it responsive.

### CODE REVIEW

**Comment by VishnuAmit** [comment]
@BarryByte Yea, that's good. Can you make the footer section responsive as well?

**Comment by BarryByte** [comment]
@VishnuAmit I have made the footer responsive. Please check.
Just to raise this issue that many things such testimonial part and its above section are colliding with each other. Shall i raise a issue for this ?

**Comment by VishnuAmit** [comment]
Yea @BarryByte , You can do that as well.

**Comment by BarryByte** [comment]
Ok, i add that.
This pr is ready to be merged.
Please review this throughout and merge.

**Comment by VishnuAmit** [comment]
hey @BarryByte just a small change.
Your PR:
image

Before:
image


Changes:
-> Maintain the logo and text overlapping like the before image.
-> Remove the white background in the placeholder and make it look like before in appearance and align the height with the subscribe button.

**Comment by BarryByte** [comment]
image

is this fine ?

**Comment by VishnuAmit** [comment]
yea, @BarryByte looks good

**Review by VishnuAmit — APPROVED** [review]
good

**Pull request merged**
