### PR TITLE
Fixes #8: Integrated AI powered chatbot

### LINKED ISSUE #8: Integrating AI-Powered Chatbot with Gemini API into the E-Learning Platform Website
### **Task Overview**
This task focuses on developing an e-learning platform with advanced features. You are tasked with integrating the **chatbot assistance** (Pro Feature 3) that is already connected to the Gemini API into the platform's website.

### **Your Role**
1. Clone the repository and run the project.
2. Install the necessary packages using `npm install`.
3. Start the application using `npm start`.
4. Once started, sign up and go to the dashboard, where you can find the button for *Pro Feature 3* (Chatbot Assistance).
5. Run the chatbot script in the backend folder using the command:

   ```bash
   python chatbot.py
# **What Needs to be Done**

## **Frontend Chat Interface:**
- Create a **chatbox** on the website where users can send queries to the chatbot.
- The UI should be **clean**, **user-friendly**, and **responsive**, allowing for seamless interaction on both desktop and mobile devices.
- Include features like **message history**, **minimization**, and **expansion** of the chat window.

## **Backend Integration:**
- Use **API calls** (such as Axios or Fetch API) to send user queries from the frontend to the backend chatbot, which is powered by the **Gemini API**.
- Ensure that **responses from the chatbot** are displayed on the frontend in real-time.

## **Real-time Communication:**
- Ensure the communication between the frontend and backend is **asynchronous**, allowing for real-time responses without page reloads.
- Use **WebSockets** or **REST API** depending on the preferred implementation, to establish this connection.


## **Feel Free to Use:**
- Any **external libraries** for frontend enhancements (e.g., **Socket.io** for real-time communication or **Axios** for making API calls).
- Design frameworks like **Bootstrap** or **Material-UI** to improve the chat interface.

### PR DESCRIPTION
**Pull request by slashexx**
Created the Chatbot.js component and dded the AI powered Gemini chatbot in the user dashboard.

Frontend is react, Backend is python (chatbot.py).

Run both chatbot.py and the react code in parallel for the chat to actually work. Of course, do put a .env file in the backend folder with (GOOGLE_API_KEY=YOUR_API_KEY) .

I was initially confused as to why the nextjs pages router wasn't working, then I realised the project was just a react project haha, so had to rewrite code in the chatbot.py

Issue: The current API call is hardcoded, i.e. the entire URL is copied in the react fetch statement which won't do. I tried to fix it but I had some trouble with the flask CORS and couldn't and shall need more time. Please create another issue for the same.

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Hi @slashexx , I have mentioned one more change. Look into it.

**Comment by VishnuAmit** [comment]
Yea @slashexx . Will create a new issue on that. (Hardcoded API call)

**Comment by slashexx** [comment]
Can we close this pull request then ?

**Comment by VishnuAmit** [comment]
hey, @slashexx. We can close it if you are done with the change that I mentioned. (Chatbot button should be fixed at the bottom right corner no matter whether or not you scroll).

**Comment by slashexx** [comment]
Fixed positioning, maybe there were the dashboard parent elements messing up with the chatbot so using 'fixed' wasn't cutting it.
Ultimately had to use react portals to render the chat bot, it even looks better now.

**Review by VishnuAmit — APPROVED** [review]
done

**Pull request merged**
