### PR TITLE
Header made Responsive, Fixed Hero Bg and Fixed Header Position

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
# Following Changes Done
- Header now have a hamburger menu on mobiles and tablets
- Hero Background doesn't look weird on high resolutions
- Header position had been made fixed so it stays on top

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Hey @Thunder-Blaze . Nice work. 
image
The logo and title should overlap. And that's the finalized logo that We have created.
cha
You can just fill this with the color. I mean lets go with rectangle.
Everything else looks better 👍

**Comment by Thunder-Blaze** [comment]
Thanks, I'll fix this by tonight
Btw how you want the logo to look ?
image
or
image

**Comment by VishnuAmit** [comment]
image

Like this.

**Comment by Thunder-Blaze** [comment]
I'll try again in an hour, I fixed the logo and the Hero Bg

**Comment by Thunder-Blaze** [comment]
Done

**Comment by VishnuAmit** [comment]
Good...

**Pull request merged**
