### PR TITLE
Implement Form Handling and Dynamic Dashboard Update in streamfinder.js , Dashboard.js & ProfileCard.js 

### PR DESCRIPTION
**Pull request by saarakhan**
This pull request implements form handling in streamfinder.js to capture Name, Institute Name, and Course Selection. Upon form submission, the Dashboard is updated to dynamically display the User Name and Institute Name.

Key Changes:

Implemented form inputs for user data in streamfinder.js.
Change the Stream selection
Updated Dashboard to reflect changes in User Name and Institute Name.

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Hey @saarakhan  looks ok but just few more changes.
- Make the stream finder form compulsory. (i mean, include required tag)
- After clicking submit, it should not go to the dashboard but prompts you to select one of the courses. After selecting it, It should go to the dashboard.
- As name and college is already getting reflected, in place of course name , the title of the course should get displayed.

**Comment by saarakhan** [comment]
All suggested changes have been made, and additional styling has been applied to the card container.

**Comment by VishnuAmit** [comment]
Looks good.

**Review by VishnuAmit — APPROVED** [review]
ok

**Comment by saarakhan** [comment]
hey can you add gssoc-ext label

**Pull request merged**
